urls.py
from django.conf.urls.defaults import *
from django.contrib.auth.views import logout, login
from django.conf import settings
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    (r'^hcb/', include('hcb.gin.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/(.*)', admin.site.root),
    url(r'^accounts/login/$',  login),
    url(r'^accounts/logout/$', logout, name="logout"),
)
if settings.DEBUG:
    from django.views.static import serve
    _media_url = settings.MEDIA_URL
    if _media_url.startswith('/'):
        _media_url = _media_url[1:]
        urlpatterns += patterns('',
            (r'^%s(?P<path>.*)$' % _media_url, serve, 
            {'document_root': settings.MEDIA_ROOT}),)
    del(_media_url, serve)

gin/models.py
#-*- coding: utf-8 -*-
from django.db import models
from django.contrib import admin
from django.contrib.auth.models import User
from django.db.models import permalink

STATUS_CHOICES = (('1','Новый'),
    ('3','В работе'),
    ('4','Отменено'),
    ('5','Решение невозможно'),
)
REGION_UKRAINE = ((1,'Киевская'),
                  (2,'Днепропетровская'),
                  (3,'Запорожская'),
                  )

CATEGORY = ((0,'Кадровые вопросы'),
            (1,'Жалобы на качество работы подразделения'))
class EmployeeProfile(models.Model):
    user = models.ForeignKey(User, unique = True)
    departament = models.CharField(max_length=50)
class EmployeeProfileAdmin(admin.ModelAdmin):
    list_display = ('user', 'departament')
admin.site.register(EmployeeProfile,EmployeeProfileAdmin)

class FormAppeal(models.Model):
    name = models.CharField('Форма обращения', max_length=20)
    def __unicode__(self):
        return "%s" % self.name
admin.site.register(FormAppeal)

class Category(models.Model):
    subcatagory = models.CharField('Подкатегория',max_length=100, blank = True)
    def __unicode__(self):
        return '%s' % self.subcatagory

admin.site.register(Category)

class Client(models.Model):
    first = models.CharField('Имя',max_length=50)
    last = models.CharField("Фамилия" ,max_length=50)
    middle_name =models.CharField('Отчество', max_length=50) 
    inn = models.DecimalField('ИНН', max_digits=10, decimal_places=0, blank= True, null=True)
    agreement = models.CharField('Договор', max_length=30, blank=True)
    region = models.IntegerField('Область', choices = REGION_UKRAINE, default='1')
    city = models.CharField('Город', max_length=30, blank=True)
    adres = models.CharField('Адрес', max_length=50, blank=True)
    postal_code = models.IntegerField('Индекс', blank = True, null=False, default = 0)
    def __unicode__(self):
        return self.first+" "+self.last
    
class ClientAdmin(admin.ModelAdmin):
    list_display = ('first','last')
admin.site.register(Client, ClientAdmin)

class Incident(models.Model):
    timestamp = models.DateTimeField(auto_now_add = True)
    title = models.CharField('Обращение',max_length=50)
    client = models.ForeignKey(Client)
    author = models.ForeignKey(User)
    responsibles = models.ManyToManyField(User, related_name='respons')
    status = models.CharField('Статус', max_length=1,choices=STATUS_CHOICES, default='1')
    incoming_number = models.CharField('Входящий номер', max_length=20)
    form_appeal = models.ForeignKey(FormAppeal, blank = True)
    data_answer_client = models.DateField('Дата ответа клиенту', blank = True, null=True)
    category = models.ForeignKey(Category, blank = True, null=True)
    class Meta:
        permissions = (
        ("can_view_all","могут видеть все"),
        ('can_close_incident','Могут закрывать инциденты')
        )

    def __unicode__(self):
        return self.title
    
    @permalink
    def get_absolute_url(self):
        return ('incident_detail',[str(self.id)])
    
    def get_list_resp(self):
        return self.responsibles.all()

class Solution(models.Model):
#Class Solution 
    author = models.ForeignKey(User)
    incident = models.ForeignKey(Incident)
    timestamp = models.DateTimeField(auto_now_add = True)
    text = models.CharField('Решение',max_length=150)
    
    def __unicode__(self):
        return str(self.author) + self.text
    
class Attachment(models.Model):
    slug = models.CharField('Описание', max_length=80)
    file_document = models.FileField(upload_to='upload_doc/')
    incident = models.ForeignKey(Incident)
    
    def __unicode__(self):
        return '%s' % self.slug

    
admin.site.register(Attachment)
admin.site.register(Incident)
admin.site.register(Solution)

templates/_cal.html
<div> {{ test }} - {{ user.username }} 
</div>

templates/archive.html
{% extends "base.html" %}
{% block content %}
        {% for post in posts %}
        <h2>{{ post.title }}</h2>
        <p>{{ post.body }}</p>
        <p>{{ post.timestamp|date }}</p>
        {% endfor %}
{% endblock %}

templates/base.html
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <title></title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <script type='text/javascript' src='{{ MEDIA_URL }}js/mootools-1.2.5-core-yc.js'></script>
    <link rel='stylesheet' href='{{ MEDIA_URL}}/css/common.css' />
  </head>
  <body>
    <script type='text/javascript'> 
      document.addEvent('domready', function(){
        $('my-link').addEvent('click', function (){
            alert('dddd');})
      })
    </script>
      <h1> Homecreditbank 'REQUEST'</h1>
      <div id="my-link"> hii {{ user.username }}</div>      
      <div id="menu">
          <a href="{% url add_inc %}">Создать новую заявку </a>
          <a href="{% url new_incident %}">Создать новую заявку 2</a>
          <a href="{% url list_inc %}">Журнал заявок</a>
          <a href="{% url logout %}"> Выйти </a>
      </div>
      {% block content %}
      {% endblock %}
  </body>
</html>

templates/detail.html
{% extends "base.html" %}
{% load mytags%}
{% block content %}
<p>Title: {{ incident.title }}</p>
{% cal %}
{% if perms.gin.can_close_incident %}
	<a href='./close'>Закрыть заявку</a> 
{% endif %} 

<form method="POST">
	{% if perms.gin.can_view_all %}
		<strong>Статус:</strong>{{ form.status }}
	{% endif %} 
	{{ form.as_p }}
	<input type="submit" value="Сохранить" name="Submit" />
</form>
{% if perms.gin.add_solution %}
	<a href='{% url gin.views.add_solution incident.id %}'>Добавить решение</a>
	<form action='{% url gin.views.add_solution incident.id %}' method="POST">
		{{ sol.as_p }}
		<input type="submit" value="Добавить решение" name="Submit" />
	</form>
{% endif %}
<a href='{% url gin.views.upload_file incident.id %}'>Добавить вложение</a>
<form method='POST' enctype="multipart/form-data" action='add_attach'>
  Вложения :
  {{ attachment.as_p }}
</form>
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block content %}
<table>
    <thead>
        <tr>
            <th>#</th>
            <th>Date</th>
            <th>Автор</th>
			<th>Отвественные<th>
            <th>Name</th>
        </tr>
    </thead>
    <tbody>
       {% for incident in incidents %}
        <tr>
	        <td><a href="{{ incident.get_absolute_url }}">{{ incident.id }}</a></td>
	       	<td>{{ incident.timestamp|date:"jS F Y H:i"  }}</td>
		    <td>{{ incident.title }}</td>
	        <td>{{ incident.author }}</td>
	        <td>{{ incident.get_list_resp }}</td>
        </tr>
      {% endfor %}
    </tbody>
</table>

 
{% endblock %}

templates/list.html
{% extends "base.html" %}
{% block content %}
<table>
    <thead>
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Author</th>
            <th>Date</th>
        </tr>
    </thead>
    <tbody>
       {% for incident in objects %}
        <tr>
        <td><a href="">{{ incident.id }}</a></td>
        <td>{{ incident.title }}</td>
        <td>{{ incident.author }}</td>
        <td>{{ incident.timestamp|date:"jS F Y H:i"  }}</td>
        </tr>
      {% endfor %}
    </tbody>
</table>

 
{% endblock %}

templates/new_inc.html
{% extends "base.html" %}
{% block content %}
<h2>Создать обращение</h2>
<form method="POST">
    {{ form.as_p }}
    {{ form_client.as_p }}
    <input type="submit" value="Сохранить" name="Submit" />
    <a class='button' href='{% url list_inc %}'>ОТМЕНА</a> 
</form>
<table></table>

{% endblock %}

templates/view_detail.html
{% extends "base.html" %}
{% load mytags%}
{% block content %}
<p>Title: {{ incident.title }}</p>
{% cal %}
Автор:{{ incident.author }}<br />
Статус: {{ incident.status }}
{% if perms.gin.can_close_incident %}
	<div><a href='./close'>Закрыть заявку</a> </div>
{% endif %} 
<form action="edit" method="" accept-charset="utf-8">
	<p><input type="submit" value="Редактировать" /></p>
</form>
{% for solution in sol %}
	{{solution.timestamp|date:"jS F Y H:i" }} :{{ solution.author }} - {{ solution.text }}  <br />
{% endfor %}
{% if perms.gin.add_solution %}
	<a href='{% url gin.views.add_solution incident.id %}'>Добавить решение</a>
{% endif %}
{% endblock %}